apiVersion: v1
kind: Pod
metadata:
  name: nodeapp1
  labels:
    app: nodeapp1
spec:
  containers:
    - name: nodeapp2
      image: anilkumblepuli/vprofile1:tagVersion
      ports:
        - containerPort: 8080
