apiVersion: v1
kind: Pod
metadata:
    name: vproapp
    labels:
      app: vproapp
spec:
    containers:
       - name: vproapp1
         image: madhu309/madhu:tagVersion
         ports:
         - name: vproapp-port
            containerPort: 8080
