apiVersion: v1
kind: Pod
metadata:
  name: madhu
  labels:
    app: madhu
spec:
  containers:
    - name: madhu
      image: madhuu309/madhu:2ea5f10dbe6c56cad3
      ports:
        - containerPort: 8080
