apiVersion: v1
kind: Pod
metadata:
  name: nodeapp2
  labels:
    app: nodeapp2
spec:
  containers:
    - name: nodeapp3
      image: madhuu309/madhu:tagVersion
      ports:
        - containerPort: 8080
