### vi vprofile-app-nodeport.yml

apiVersion: v1
kind: Service
metadata:
 name: vproapp-service2
spec:
  ports:30001
   - port: 
     nodePort: 30001
     targetPort: 8080
     protocol: TCP
  selector:
      app: node-app2
  type: NodePort
